version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

  receiver:
    build: ./receiver-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis

  listener:
    build: ./listener-service
    depends_on:
      - mongo
      - redis

volumes:
  mongo-data:
